name: 'GitOps Pull Request'
description: 'Update an image tag and create pull request'
author: Jakpat Mingmongkolmitr
inputs:
  config-path:
    description: 'Relative path under `GITHUB_WORKSPACE` to the config file'
    required: true
  image:
    description: 'Image URI'
    required: true
  token:
    description: 'Github personal access token'
    required: true
  version:
    description: 'Semantic version of the deployment'
    required: true
  vars:
    description: 'Extra variables to inflate the template config'
outputs:
  pull-number:
    description: 'Created pull request number'
runs:
  using: 'node16'
  main: 'dist/index.js'
