name: 'GitOps Pull Request'
description: 'Update an image tag and create pull request'
author: Jakpat Mingmongkolmitr
inputs:
  configPath:
    description: 'Relative path under `GITHUB_WORKSPACE` to the config file'
    required: true
  image:
    description: 'Image URI'
    required: true
  token:
    description: 'Github personal access token'
    required: true
  version:
    description: 'Semantic version of the deployment'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
