on:
  push:
    branches: [release/v1]

name: Test GitOps PR Action

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GitOps via kustomize
        uses: WhatTheFar/gitops-pr-action@v1-beta
        with:
          configPath: fixtures/gitops.kustomize.yml
          image: hello-world:v1.0.0
          token: ${{ github.token }}
          version: v1.0.0
