on:
  push:
    tags:
      - v1-beta

name: Test GitOps PR Action

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: GitOps via kustomize
        id: gitops
        uses: WhatTheFar/gitops-pr-action@v1-beta
        with:
          config-path: kustomize/gitops.vars.yml
          image: hello-world:v1-beta
          token: ${{ github.token }}
          version: v1-beta-${{ github.sha }}
          vars: |
            Name: hello-world

      - name: Clean up
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh pr close --delete-branch ${{ steps.gitops.outputs.pull-number }}
