on:
  push:
    tags:
     - v1-beta

name: Test GitOps PR Action

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GitOps via kustomize
        uses: WhatTheFar/gitops-pr-action@v1-beta
        with:
          config-path: fixtures/gitops.kustomize.yml
          image: hello-world:v1-beta
          token: ${{ github.token }}
          version: v1-beta-${{ github.sha }}
